In [8]:
import numpy as np


# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [65]:
arr = np.linspace(0, 20, 28).reshape(4, 7)
arr

array([[ 0.        ,  0.74074074,  1.48148148,  2.22222222,  2.96296296,
         3.7037037 ,  4.44444444],
       [ 5.18518519,  5.92592593,  6.66666667,  7.40740741,  8.14814815,
         8.88888889,  9.62962963],
       [10.37037037, 11.11111111, 11.85185185, 12.59259259, 13.33333333,
        14.07407407, 14.81481481],
       [15.55555556, 16.2962963 , 17.03703704, 17.77777778, 18.51851852,
        19.25925926, 20.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [64]:
rnd_arr = np.random.randint(0, 10, size=(8, 10)) 
i = np.where(np.sum(rnd_arr, axis=1) == min(np.sum(rnd_arr, axis=1)))
rnd_arr, rnd_arr[i], i

(array([[0, 1, 1, 8, 6, 9, 2, 5, 1, 0],
        [9, 9, 0, 5, 9, 7, 7, 2, 7, 4],
        [1, 7, 7, 9, 6, 8, 9, 2, 6, 1],
        [0, 6, 7, 5, 9, 5, 6, 4, 6, 2],
        [4, 2, 3, 6, 0, 8, 5, 6, 1, 4],
        [0, 4, 8, 9, 5, 1, 8, 9, 3, 8],
        [0, 1, 3, 4, 2, 7, 5, 6, 8, 3],
        [1, 5, 7, 1, 4, 8, 9, 0, 7, 5]]),
 array([[0, 1, 1, 8, 6, 9, 2, 5, 1, 0]]),
 (array([0]),))

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [63]:
a = np.array([0, 0, 0, 13])
b = np.array([6, 4, 0, 2])
sum((a-b)**2)**0.5

13.152946437965905

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [62]:
A = np.matrix(
    [[-1, 2, 4], 
     [-3, 1, 2], 
     [-3, 0, 1]])

B = np.matrix(
    [[3, -1], 
     [2, 1]])

C = np.matrix(
    [[7, 21], 
     [11, 8], 
     [8, 4]])

x = np.linalg.inv(A)*(-C)*np.linalg.inv(B)
x

matrix([[ 1.00000000e+00,  5.32907052e-16],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [66]:
a = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',', skiprows=1)
a[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [67]:
for i in range(1, a.shape[1]):
    print(f'min = {a[:, i].min()} max = {a[:, i].max()}, mean = {a[:, i].mean()}, median = {np.median(a[:, i])}')

min = 0 max = 2147483647, mean = 21601.00169, median = 40.0
min = 1 max = 39, mean = 9.05528, median = 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [68]:
q = np.quantile(a[:, 1], 0.75)
print(q)
a[:, 1] = np.where(a[:, 1] > q, q, a[:, 1])
a

65.0


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [69]:
print(np.count_nonzero(a[:, 1] == 0))
a[:, 1] = np.where(a[:, 1] != 0, a[:, 1], 1)
a

479


array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]], dtype=int32)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [70]:
len(np.unique(a[:, 1:3]))

65

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [71]:
len(np.unique(a[:, 2])), np.unique(a[:, 2])

(37,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [72]:
short_cut = a[np.where(a[:, 2] <= 5)[0]]
short_cut, short_cut.shape

(array([[446597,     15,      5],
        [204134,      5,      3],
        [ 25623,      6,      4],
        ...,
        [ 52088,     60,      5],
        [128811,     15,      4],
        [370915,      5,      4]], dtype=int32),
 (17262, 3))

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [61]:
np.max(a[:, 2]/a[:, 1]), a[:, 2]/a[:, 1]

(24.0,
 array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.21538462]))

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [75]:
sorted_indices = np.argsort(a[:, 1])[-100:]
sorted_array = a[sorted_indices]
sorted_array[:, 2].mean()

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [78]:
idx = np.random.randint(a.shape[0], size=10)
a[idx, :]

array([[233490,     30,     19],
       [140003,     55,      4],
       [291257,     65,     10],
       [ 88890,     65,      9],
       [224578,      6,      5],
       [194597,     60,     15],
       [349684,     25,      6],
       [348897,     35,     11],
       [399369,     20,      5],
       [263815,     55,      7]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [80]:
str(len(np.where(a[:, 2] < a[:, 2].mean())[0])/a.shape[0]*100) + '%'

'58.802%'

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [81]:
good_recepts = np.zeros((a.shape[0], 4), dtype=int) 
good_recepts[:, :3] = a 
good_recepts[np.where((a[:, 2] <= 5) & (a[:, 1] <= 20)), 3] = 1
good_recepts

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [83]:
 str(sum(good_recepts[:, 3])/a.shape[0]*100) + '%'

'9.552%'

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [84]:
short_recipes = a[a[:, 1] < 10]
standard_recipes = a[(a[:, 1] >= 10) & (a[:, 1] < 20)]
long_recipes = a[a[:, 1] >= 20]

max_length = min(len(short_recipes), len(standard_recipes), len(long_recipes))

three_dimensional_array = np.zeros((3, max_length, 3), dtype=int)

three_dimensional_array[0, :max_length, :] = short_recipes[:max_length]
three_dimensional_array[1, :max_length, :] = standard_recipes[:max_length]
three_dimensional_array[2, :max_length, :] = long_recipes[:max_length]

three_dimensional_array.shape, three_dimensional_array

((3, 7588, 3),
 array([[[ 67660,      5,      6],
         [366174,      7,      9],
         [204134,      5,      3],
         ...,
         [420725,      5,      3],
         [  4747,      1,      9],
         [370915,      5,      4]],
 
        [[ 94746,     10,      6],
         [ 33941,     18,      9],
         [446597,     15,      5],
         ...,
         [  9831,     15,      7],
         [335859,     12,     14],
         [256812,     10,      3]],
 
        [[127244,     60,     16],
         [ 23891,     25,      7],
         [157911,     60,     14],
         ...,
         [168901,     25,      7],
         [392339,     35,     13],
         [206732,     45,     10]]]))